services:
  mongo:
    image: mongo:7
    restart: always
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  webapp:
    build: .
    container_name: my-webapp
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yourDatabaseName  # Updated for local MongoDB
      - GOOGLE_CLIENT_ID=110723506551-qj7263vnrkiffl9v0npjhehs6q86596p.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NEXTAUTH_SECRET=hitcon.859477
      - GMAIL_USER=rezwanwarrior@gmail.com
      - GMAIL_PASS=ypsardborjyqrckr
    depends_on:
      - mongo
    volumes:
      - ./:/app  # Optional: For development (hot-reload)

volumes:
  mongo-data: