version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: always
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  webapp:
    build: .
    container_name: my-webapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data: